# Generated by Django 4.1.7 on 2023-04-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaminacionAcustica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decibelios', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ContaminacionDelAire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm', models.FloatField()),
                ('co', models.FloatField()),
                ('no2', models.FloatField()),
                ('co2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
                ('alcance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Reciclaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
                ('horarios', models.CharField(max_length=1000)),
                ('cod_localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.localizacion')),
            ],
        ),
    ]
