# Generated by Django 4.1.7 on 2023-04-29 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Aplicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='cod_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contaminaciondelaire',
            name='cod_localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.localizacion'),
        ),
        migrations.AddField(
            model_name='contaminaciondelaire',
            name='cod_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.sensor'),
        ),
        migrations.AddField(
            model_name='contaminacionacustica',
            name='cod_localizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.localizacion'),
        ),
        migrations.AddField(
            model_name='contaminacionacustica',
            name='cod_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.sensor'),
        ),
    ]
